[project]
name = "github-issue-triage-copilot-agentic101"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ismail hamdaoui", email = "ismailhamdaoui101@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "mcp[cli]>=2.2.0",
]

[project.scripts]
github-issue-triage-copilot-agentic101 = "github_issue_triage_copilot_agentic101:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
